"""Layer 4 - the modules in the Year 1 kit, Keyestudio KS4011 Honeycomb.

Hexagonal modules with conductive rings, joined with alligator clips. Every ring
is labelled on the board, so pin lists here use the teacher's own labels rather
than catalogue names.

Confidence is uneven on purpose. The 5050 RGB module carries a direct quote from
Keyestudio's own project page; several others carry NOT VERIFIED, because the
published material for this kit shows the wiring photo and the finished code
without ever stating which level is the active one. Guessing them would defeat
the point of the exercise - an unverified profile still helps, because it tells
the assistant to say "I cannot confirm" instead of inventing an answer that
sounds exactly as confident as a real one.
"""

from __future__ import annotations

from app.services.hardware.schema import (
    Analog,
    Category,
    CodeNotes,
    Component,
    Digital,
    Direction,
    Electrical,
    LedCommon,
    MicrobitNotes,
    Polarity,
    Pwm,
    Signal,
    Teaching,
    Verification,
    Verified,
)

KIT = "KS4011"
DOCS = "https://docs.keyestudio.com/projects/KS4011/en/latest/KS4011.html"

# Read off the manufacturer's own project pages.
KEYESTUDIO = Verification(
    status=Verified.manufacturer_doc,
    source="Keyestudio KS4011 project documentation",
    source_url=DOCS,
    last_verified="2026-08-30",
)
# True of this type of part everywhere, not confirmed against this module's own
# schematic. Renders to the teacher with the caveat attached.
PART_TYPE = Verification(
    status=Verified.general_knowledge,
    source="Standard behaviour of this part type",
    notes="Confirm against the module before teaching it as fact.",
)
# Keyestudio publishes a photo and working code for these and never says which
# level is active. Left honest rather than filled in.
UNCHECKED = Verification(
    status=Verified.needs_verification,
    source="Keyestudio KS4011 project pages do not state the active level",
    source_url=DOCS,
    notes="Needs one reading from the physical module to settle.",
)

# Every honeycomb module shares this. Repeating it per component would be noise;
# it belongs to the kit's construction, not to any one part.
_RINGS = "Alligator clip onto the labelled rings. V to 3V, G to GND, S (or the colour letters) to the signal pin."

COMPONENTS: tuple[Component, ...] = (
    Component(
        id="ks4011-microbit-board",
        name="micro:bit Main Board",
        kits=(KIT,),
        category=Category.board,
        manufacturer="BBC / Micro:bit Educational Foundation",
        summary="The micro:bit itself, which this kit includes. Its pin capabilities are in the micro:bit layer, not here - the board is not a component wired to itself.",
        aliases=("microbit", "micro:bit board", "main board"),
        doc_url=DOCS,
        electrical=Electrical(
            operating_voltage="3.3 V logic, powered over USB or from the battery connector",
            polarity=Polarity.not_applicable,
        ),
        verification=KEYESTUDIO,
    ),
    Component(
        id="ks4011-expansion-board",
        name="micro:bit Expansion Board",
        kits=(KIT,),
        category=Category.breakout,
        summary="Breaks the micro:bit edge connector out to labelled headers so several modules can share 3V and GND.",
        aliases=("expansion board", "breakout board", "shield"),
        doc_url=DOCS,
        signals=(Signal.none,),
        electrical=Electrical(
            operating_voltage="Passes the micro:bit's 3.3 V through",
            pins=("One V/G/S group per micro:bit pin",),
            polarity=Polarity.not_applicable,
        ),
        microbit=MicrobitNotes(
            wiring="It renames nothing. A module on the board's P0 group is on micro:bit P0, with the same sharing rules.",
            conflicts="It does not add current. Everything plugged in still draws from the micro:bit's 3V regulator.",
        ),
        teaching=Teaching(
            beginner="A power strip for signals: one 3V and one GND from the micro:bit, shared out to every module.",
            mistakes=("Assuming the board isolates or protects the micro:bit's pins. It does not - it only re-routes them.",),
        ),
        verification=KEYESTUDIO,
    ),
    Component(
        id="ks4011-5050-rgb",
        name="5050 RGB Module",
        kits=(KIT,),
        category=Category.light,
        summary="One 5050 RGB LED with three colour channels brought out to separate rings. Common-anode, so each channel is active-LOW.",
        aliases=("rgb module", "rgb led", "5050 rgb", "rgb", "colour led", "color led"),
        doc_url="https://docs.keyestudio.com/projects/KS4011/en/latest/docs/3.%20Microbit/Project/Project17.html",
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3 V from the micro:bit 3V ring",
            pins=("R - red channel signal", "G - green channel signal", "B - blue channel signal", "V - 3V (three V rings, connected together)"),
            signal_channels=3,
            polarity=Polarity.active_low,
            led_common=LedCommon.anode,
            onboard_resistor="Current limiting is on the module. Do not add a resistor.",
            current_notes="Three channels lit at once draw the most; well within the 3V ring's budget on its own.",
        ),
        digital=Digital(
            high_means="That colour channel is OFF. The pin and the common anode are both near 3.3 V, so no current flows through that LED.",
            low_means="That colour channel is ON. The pin sinks current from the 3 V common anode down through that colour.",
            active_state="LOW",
            inactive_state="HIGH",
            resting_state="Write HIGH to R, G and B to leave the LED dark.",
        ),
        pwm=Pwm(
            value_range="0-1023 via analog write",
            increasing_duty="Higher numbers make that channel DIMMER, because the channel is active-low: a larger duty cycle spends more time HIGH, which is off. 0 is fullest brightness, 1023 is dark.",
            useful_range="Invert the value you would use on an active-high LED: 1023 minus your intended brightness.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="P0, P1, P2 - the three large rings, all analog and PWM capable.",
            wiring="V ring to 3V, then one colour ring per signal pin. There is no separate ground ring: the return path is through the micro:bit pin when it is driven LOW.",
            conflicts="Using P3, P4, P6, P7, P9 or P10 for a colour requires turning the LED display off first.",
        ),
        makecode=CodeNotes(
            write="pins.digitalWritePin(DigitalPin.P1, 0) lights red. pins.analogWritePin(AnalogPin.P1, 1023) turns red off.",
            notes="Not a NeoPixel. The NeoPixel extension does not apply here - these are three ordinary pins.",
        ),
        micropython=CodeNotes(
            write="pin1.write_digital(0) lights red; pin1.write_digital(1) turns it off. pin1.write_analog(0) is full red.",
            notes="Same three pins, same active-low behaviour as MakeCode.",
        ),
        teaching=Teaching(
            beginner="All three colours share one positive leg held at 3 V. A colour lights when its pin pulls the other end DOWN to 0 V, so 0 is on and 1 is off for this module.",
            mistakes=(
                "Expecting 1 to light a colour. It does the opposite on this module.",
                "Expecting a bigger analog value to be brighter. It is dimmer here.",
                "Adding an external resistor. The module already has them.",
            ),
            troubleshooting=(
                "All three colours on at once and nothing responds: the V ring is on GND instead of 3V.",
                "One colour permanently on: that colour's ring is clipped to GND rather than to a pin. Keyestudio's own project does exactly this to green.",
            ),
            terms=("common anode", "active-low", "colour channel"),
        ),
        verification=Verification(
            status=Verified.manufacturer_doc,
            source='Keyestudio KS4011 Project 17, which states the control mode as "active LOW(common anode)"',
            source_url="https://docs.keyestudio.com/projects/KS4011/en/latest/docs/3.%20Microbit/Project/Project17.html",
            last_verified="2026-08-30",
            notes="Both kits' RGB modules are common-anode. Do not generalise that to RGB modules elsewhere.",
        ),
    ),
    Component(
        id="ks4011-1w-led",
        name="1W LED Module",
        kits=(KIT,),
        category=Category.light,
        summary="A single high-brightness 1 W white LED on its own module.",
        aliases=("1w led", "white led", "bright led", "1 w led"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="On-board. Do not add one.",
            current_notes="The brightest draw in this kit. Run it from the 3V ring, not from a signal pin used as a supply.",
        ),
        digital=Digital(
            high_means="LED on.",
            low_means="LED off.",
            active_state="HIGH",
            inactive_state="LOW",
        ),
        pwm=Pwm(
            value_range="0-1023 via analog write",
            increasing_duty="Brighter. 0 is off, 1023 is full brightness.",
            useful_range="Below about 50 the LED is visibly stepping rather than dimming smoothly.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any PWM-capable pin; P0, P1 or P2 for dimming.", wiring=_RINGS),
        teaching=Teaching(
            beginner="One LED, one pin. HIGH lights it because the LED's positive side is the signal ring on this module.",
            safety="Do not look straight into it at full brightness.",
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-digital-led",
        name="Digital LED Module",
        kits=(KIT,),
        category=Category.light,
        summary="A single-colour indicator LED driven from one pin.",
        aliases=("digital led",),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="On-board.",
        ),
        digital=Digital(
            high_means="LED on.",
            low_means="LED off.",
            active_state="HIGH",
            inactive_state="LOW",
        ),
        pwm=Pwm(value_range="0-1023", increasing_duty="Brighter."),
        microbit=MicrobitNotes(wiring=_RINGS),
        teaching=Teaching(
            beginner="The simplest output in the kit and the usual first project.",
            mistakes=("Assuming every LED in the kit works this way. The 5050 RGB module is the opposite.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-traffic-light",
        name="Traffic Light Module",
        kits=(KIT,),
        category=Category.light,
        summary="Red, yellow and green LEDs on one module, one signal ring each.",
        aliases=("traffic light", "traffic lights", "stop light"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("R - red signal", "Y - yellow signal", "G - green signal", "V - 3V", "GND"),
            signal_channels=3,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="One per LED, on-board.",
        ),
        digital=Digital(
            high_means="That LED on.",
            low_means="That LED off.",
            active_state="HIGH",
            inactive_state="LOW",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Three separate pins, one per colour. P0, P1, P2 is the usual choice.",
            wiring=_RINGS,
            conflicts="Needs three pins at once, so watch what else is connected.",
        ),
        teaching=Teaching(
            beginner="Three independent LEDs that happen to share a board. Nothing sequences them - the code does.",
            mistakes=("Expecting the module to enforce a sequence. It has no logic on board.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-passive-buzzer",
        name="Passive Buzzer",
        kits=(KIT,),
        category=Category.sound,
        summary="A passive buzzer: it has no oscillator, so it only makes sound when the signal itself alternates at an audible frequency.",
        aliases=("passive buzzer", "buzzer", "speaker", "sounder"),
        doc_url=DOCS,
        signals=(Signal.pwm, Signal.digital_out),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            current_notes="Small. Safe from the 3V ring.",
        ),
        digital=Digital(
            high_means="The element is held deflected. A steady HIGH is silent, or gives one faint click as it moves.",
            low_means="The element is held at rest. A steady LOW is silent.",
            active_state="Not a level at all - sound needs the signal to keep changing.",
            inactive_state="Any unchanging level.",
        ),
        pwm=Pwm(
            value_range="Frequency is what matters here, not duty cycle.",
            increasing_duty="Louder up to a point, but it does NOT change the pitch. Pitch comes from the frequency.",
            frequency="The frequency IS the note. Roughly 100 Hz to 5 kHz is useful; the audible ceiling of these elements is a few kilohertz.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="P0 by default - MakeCode and MicroPython both send music there unless told otherwise.",
            version_notes="On micro:bit V2 the on-board speaker plays the same music, so a teacher can hear a tune while the buzzer is silently disconnected. On V1 silence means the wiring is wrong.",
            wiring=_RINGS,
        ),
        makecode=CodeNotes(
            write="music.playTone(Note.C, music.beat(BeatFraction.Whole)). The music blocks generate the alternating signal for you.",
            notes="An ordinary digital write will not produce a tone from this buzzer.",
        ),
        micropython=CodeNotes(
            setup="import music",
            write="music.pitch(440, 500) plays 440 Hz for half a second.",
            notes="pin0.write_digital(1) produces no tone from a passive buzzer.",
        ),
        teaching=Teaching(
            beginner="Passive means no oscillator inside. The micro:bit has to do the shaking. That is why it needs a music block or a pitch call, not just switching a pin on.",
            mistakes=(
                "Turning it on with a digital write and concluding it is broken.",
                "Reaching for analog write to change the note. Duty cycle changes volume; frequency changes pitch.",
            ),
            troubleshooting=("Silent on a V2: check you are not hearing only the on-board speaker.",),
            terms=("passive buzzer", "frequency", "duty cycle"),
        ),
        verification=Verification(
            status=Verified.manufacturer_doc,
            source="Keyestudio KS4011 parts list, which names the part as a passive buzzer",
            source_url=DOCS,
            last_verified="2026-08-30",
            notes="The active/passive identity is from the parts list. Loudness behaviour is general knowledge.",
        ),
    ),
    Component(
        id="ks4011-button",
        name="Tactile Button Module",
        kits=(KIT,),
        category=Category.input_control,
        summary="A momentary push button on a module. Which level it reads when pressed is not stated by the manufacturer.",
        aliases=("button module", "tactile button", "push button", "button"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
            pull_resistor="A pull resistor is on the module, but its direction has not been confirmed.",
        ),
        digital=Digital(
            high_means="unknown - depends on whether this module pulls up or down, which is not documented.",
            low_means="unknown - see above.",
            active_state="unknown",
            inactive_state="unknown",
            resting_state="Stable, not floating. The module holds the line one way when the button is open.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any digital pin. Avoid P5 and P11, which are the micro:bit's own buttons A and B.",
            wiring=_RINGS,
        ),
        makecode=CodeNotes(read="pins.digitalReadPin(DigitalPin.P0)"),
        micropython=CodeNotes(read="pin0.read_digital()"),
        teaching=Teaching(
            beginner="A switch and a resistor. The resistor decides what the pin reads when nobody is pressing, and that is what sets whether pressed reads 0 or 1.",
            troubleshooting=(
                "Settle it in ten seconds: show the pin's value on the display, then press. Whatever it changes to is the pressed level for this module.",
            ),
            mistakes=("Copying the pressed level from micro:bit buttons A and B. Those read LOW when pressed; a module need not.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4011-touch",
        name="Capacitive Touch Module",
        kits=(KIT,),
        category=Category.sensor_touch,
        summary="A capacitive touch pad, typically a TTP223 chip, which registers a finger without any moving part.",
        aliases=("capacitive touch", "touch module", "touch sensor", "touch pad"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            pull_resistor="Driven by the chip; no external resistor needed.",
        ),
        digital=Digital(
            high_means="Touched.",
            low_means="Not touched.",
            active_state="HIGH",
            inactive_state="LOW",
            triggered_state="HIGH while the finger is on the pad, in the chip's default mode.",
            resting_state="LOW",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any digital pin.",
            version_notes="Different from the micro:bit V2 touch logo, which is a separate feature on the board itself.",
            wiring=_RINGS,
        ),
        teaching=Teaching(
            beginner="It measures the capacitance a finger adds, so it works through a thin sticker or sheet of paper but not through metal.",
            mistakes=("Expecting it to work through a thick case or with gloves.",),
            troubleshooting=("Triggering on its own usually means the module is sitting on something conductive, or the power is noisy.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-vibration-tilt",
        name="Vibration Tilt Module",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="A ball-in-tube switch that closes when the module is tilted or knocked. Its output level is not documented.",
        aliases=("vibration tilt", "tilt module", "vibration module", "tilt switch", "shake sensor"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(
            high_means="unknown for this module.",
            low_means="unknown for this module.",
            active_state="unknown",
            inactive_state="unknown",
            triggered_state="The switch closes when tilted past its angle or shaken. Which level that produces is unconfirmed.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_RINGS),
        teaching=Teaching(
            beginner="A tiny ball that rolls across two contacts. It is a switch, not a measurement - there is no angle reading.",
            mistakes=(
                "Expecting a tilt angle. It gives one bit.",
                "Polling it once per second and missing the bounce. Read it in a fast loop or use an event.",
            ),
            troubleshooting=("Chatters on every read: that is contact bounce, and it is normal. Debounce in code.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4011-hall",
        name="Hall Magnetic Sensor",
        kits=(KIT,),
        category=Category.sensor_magnetic,
        summary="Detects a nearby magnet. Hall modules exist in both active-high and active-low forms and this one is not documented.",
        aliases=("hall sensor", "hall magnetic", "magnet sensor", "magnetic sensor"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(
            high_means="unknown for this module.",
            low_means="unknown for this module.",
            active_state="unknown",
            inactive_state="unknown",
            triggered_state="A magnet close to the chip. Many Hall switches are open-drain and pull LOW when triggered, but that has not been confirmed here.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any digital pin.",
            conflicts="Different from the micro:bit's own compass, which measures a field strength rather than switching.",
            wiring=_RINGS,
        ),
        teaching=Teaching(
            beginner="A magnetic switch. Many types care which magnetic pole faces them, so if nothing happens, turn the magnet over before assuming it is broken.",
            troubleshooting=("Display the pin value and bring a magnet up to it - the level it changes to is this module's triggered level.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4011-pir",
        name="PIR Motion Module",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="Passive infrared motion detector: it senses a warm body moving across its field of view.",
        aliases=("pir", "pir motion", "motion sensor", "movement sensor", "infrared motion"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
        ),
        digital=Digital(
            high_means="Motion detected, and it stays HIGH for a short hold time after the movement stops.",
            low_means="No motion in the hold window.",
            active_state="HIGH",
            inactive_state="LOW",
            triggered_state="HIGH",
            resting_state="LOW",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_RINGS),
        teaching=Teaching(
            beginner="Passive means it emits nothing; it only watches for a change in the infrared already in the room. It reacts to MOVEMENT, so someone sitting still disappears from it.",
            mistakes=(
                "Expecting it to detect a present but motionless person.",
                "Testing it in the first minute after power-up, while it is still settling.",
            ),
            troubleshooting=(
                "Constant HIGH just after power-on is normal - give it up to a minute.",
                "Triggering at nothing: it also sees a radiator, sunlight moving across a wall, or a draught.",
            ),
            terms=("passive infrared", "hold time", "warm-up"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-photoresistor",
        name="Photoresistor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="A light-dependent resistor in a divider, read as an analog value. The direction of the reading is not documented.",
        aliases=("photoresistor", "ldr", "light dependent resistor", "light sensor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - analog signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023 on a micro:bit analog pin",
            direction=Direction.unknown,
            calibration="Settle it in ten seconds: show the reading on the display, then cup your hand over the sensor. If the number falls, more light means a higher value; if it rises, the opposite. Note it down for the lesson.",
            environment="Room lighting, window position and time of day all shift it, so a threshold that works in one classroom will not transfer to another.",
            threshold="Choose the threshold from the two readings you just took - bright and covered - not from a number in a worksheet.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="P0, P1, P2, P3, P4 or P10 only. The other pins cannot read analog.",
            wiring=_RINGS,
        ),
        makecode=CodeNotes(read="pins.analogReadPin(AnalogPin.P0)"),
        micropython=CodeNotes(read="pin0.read_analog()"),
        teaching=Teaching(
            beginner="Its resistance falls as light rises. Whether that makes the NUMBER go up or down depends on which side of the divider the micro:bit is reading, which is a property of this module.",
            mistakes=(
                "Assuming a bigger number always means brighter.",
                "Reusing a threshold from another room.",
            ),
            terms=("voltage divider", "analog", "threshold", "calibration"),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4011-temt6000",
        name="TEMT6000 Ambient Light Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="A phototransistor light sensor, closer to human eye response than a photoresistor and faster to react.",
        aliases=("temt6000", "ambient light sensor", "light sensor module"),
        model="TEMT6000",
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - analog signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            calibration="Confirm with the cover-it test before relying on the direction in a lesson.",
            environment="Responds to visible light much like an eye does, so it tracks 'how bright does this look' better than a photoresistor.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin: P0, P1, P2, P3, P4 or P10.", wiring=_RINGS),
        teaching=Teaching(
            beginner="A phototransistor: more light lets more current through, which raises the voltage the micro:bit reads.",
            mistakes=("Treating it and the photoresistor as interchangeable. They respond to different parts of the spectrum, at different speeds.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-sound",
        name="Sound Sensor",
        kits=(KIT,),
        category=Category.sensor_sound,
        summary="A microphone with an amplifier, read as an analog loudness level.",
        aliases=("sound sensor", "microphone", "noise sensor", "mic"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - analog signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="A quiet classroom does not read 0. There is a resting level, and loudness shows up as movement above it.",
            calibration="Read it for a few seconds in silence to find the resting level, then trigger on the difference from that, not on an absolute number.",
            environment="Fans, projectors and corridor noise all raise the floor.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="An analog-capable pin.",
            version_notes="micro:bit V2 has its own microphone. This module is the only option on V1.",
            wiring=_RINGS,
        ),
        teaching=Teaching(
            beginner="It reports instantaneous loudness, not a running average, so a single reading catches whatever the waveform was doing at that moment. Sample repeatedly and take the peak.",
            mistakes=("Expecting silence to read zero.", "Taking one sample and calling it the noise level.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-potentiometer",
        name="Rotary Potentiometer Module",
        kits=(KIT,),
        category=Category.input_control,
        summary="A knob the student turns, read as an analog value. The kit's clearest example of an analog input.",
        aliases=("potentiometer", "rotary potentiometer", "knob", "pot", "dial"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - analog signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            minimum="Near 0 at one end stop.",
            maximum="Near 1023 at the other.",
            typical_values="It may not reach exactly 0 or exactly 1023. Map from what it actually reaches.",
            calibration="Read both end stops once and use those numbers, rather than assuming the full range.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin: P0, P1, P2, P3, P4 or P10.", wiring=_RINGS),
        teaching=Teaching(
            beginner="A voltage divider you can turn. The wiper picks off a fraction of 3.3 V and the micro:bit converts that to 0-1023.",
            mistakes=("Wiring the outer legs to the pin and the wiper to power. Only the wiper carries the varying voltage.",),
            terms=("voltage divider", "wiper", "analog read"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-joystick",
        name="PS2 Joystick Module",
        kits=(KIT,),
        category=Category.input_control,
        summary="A two-axis thumbstick with a push switch: two analog outputs plus one digital.",
        aliases=("joystick", "ps2 joystick", "thumbstick", "stick"),
        doc_url=DOCS,
        signals=(Signal.analog_in, Signal.digital_in),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("X - analog, horizontal", "Y - analog, vertical", "B - digital, the push switch", "V - 3V", "G - GND"),
            signal_channels=3,
            polarity=Polarity.unknown,
        ),
        analog=Analog(
            raw_range="0-1023 per axis",
            direction=Direction.more_is_higher,
            typical_values="Centred sits near the middle of the range, usually around 500, and rarely at exactly 512.",
            calibration="Read the centre value at rest and treat that as zero, with a dead band either side. Without one the value drifts and the robot creeps.",
        ),
        digital=Digital(
            high_means="unknown - the button's pressed level is not documented for this module.",
            low_means="unknown - see above.",
            active_state="unknown",
            inactive_state="unknown",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Two analog-capable pins for X and Y, any digital pin for the button. That is three pins.",
            conflicts="Three pins is a lot on a micro:bit. Check what else is connected before adding it.",
            wiring=_RINGS,
        ),
        teaching=Teaching(
            beginner="Two potentiometers at right angles plus a button. Nothing new - just three inputs in one part.",
            mistakes=("Assuming the centre is exactly 512.", "Forgetting a dead band, then wondering why the output never rests.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4011-soil",
        name="Soil Humidity Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="Two probes read as an analog value that tracks how conductive the soil between them is.",
        aliases=("soil humidity", "soil moisture", "moisture sensor", "soil sensor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("S - analog signal", "V - 3V", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.unknown,
            calibration="Take two readings and write them into the lesson: probes in air (dry) and probes in a glass of water (wet). Everything else is between those. Which end is the larger number is a property of this module.",
            environment="Fertiliser and tap-water minerals change conductivity, so the same wetness reads differently in different soil.",
            threshold="Set it from the two calibration readings, not from a number in a worksheet.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_RINGS),
        teaching=Teaching(
            beginner="It measures how easily electricity crosses between the probes. Wet soil conducts better than dry soil - that is the whole principle.",
            mistakes=(
                "Assuming a higher number means wetter. Confirm with the air-and-water test.",
                "Calling the reading a percentage. It is a raw value until you map it.",
            ),
            troubleshooting=("Readings drift over weeks: the probes corrode when powered continuously. Power it only while taking a reading.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4011-color",
        name="TCS34725FN Colour Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="An I2C colour sensor returning red, green, blue and clear channels, with its own white LED to light the target.",
        aliases=("colour sensor", "color sensor", "tcs34725", "rgb sensor"),
        model="TCS34725FN",
        doc_url=DOCS,
        signals=(Signal.i2c,),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("SCL - I2C clock", "SDA - I2C data", "V - 3V", "G - GND"),
            signal_channels=2,
            polarity=Polarity.not_applicable,
        ),
        microbit=MicrobitNotes(
            suggested_pins="SCL to P19 and SDA to P20. Nowhere else - those are the micro:bit's I2C bus.",
            avoid_pins="Do not put it on P0-P2 and try to read it as analog. It has no analog output.",
            conflicts="Shares the bus with the on-board accelerometer and compass. That is fine - I2C is designed for it - but the pins are not free for anything else.",
            wiring="Four clips: SCL to P19, SDA to P20, V to 3V, G to GND.",
        ),
        makecode=CodeNotes(
            extension="Needs a TCS34725 extension added in MakeCode. Without it there are no blocks for this sensor.",
            read="Extension blocks return the red, green, blue and clear channels.",
        ),
        micropython=CodeNotes(
            notes="No built-in driver. It needs I2C register reads, or a driver module supplied with the lesson - a step up from the other sensors in this kit.",
        ),
        teaching=Teaching(
            beginner="Not one reading but four: red, green, blue and overall brightness. Colour is worked out from the ratios between them, which is why the on-board LED matters - it keeps the lighting constant.",
            mistakes=(
                "Wiring it to an analog pin. It talks over I2C and gives nothing on a plain pin.",
                "Comparing raw values across different room lighting instead of comparing ratios.",
            ),
            troubleshooting=("Reads nothing at all: SCL and SDA swapped, or the extension is missing.",),
            terms=("I2C", "SCL", "SDA", "clear channel"),
        ),
        verification=PART_TYPE,
    ),
    # The parts with no electrical behaviour to describe. Present so the kit's
    # printed list maps completely onto the catalogue - a part that is simply
    # missing looks the same as one nobody has written up yet.
    Component(
        id="ks4011-usb-cable",
        name="Black USB Cable",
        kits=(KIT,),
        category=Category.passive,
        summary="Programs and powers the micro:bit from a computer.",
        aliases=("usb cable",),
        signals=(Signal.none,),
        electrical=Electrical(operating_voltage="5 V from USB", polarity=Polarity.not_applicable),
        verification=KEYESTUDIO,
    ),
    Component(
        id="ks4011-clips",
        name="Alligator Clip Cables",
        kits=(KIT,),
        category=Category.passive,
        summary="Ten clip leads. This kit's only way of joining modules - it has no jumper wires and no breadboard.",
        aliases=("alligator clips", "crocodile clips", "clip cables"),
        signals=(Signal.none,),
        electrical=Electrical(polarity=Polarity.not_applicable),
        teaching=Teaching(
            troubleshooting=("Clips touching each other is the commonest cause of an inexplicably dead circuit. The large micro:bit rings sit close together.",),
        ),
        verification=KEYESTUDIO,
    ),
    Component(
        id="ks4011-battery-holder",
        name="2 x AA Battery Holder",
        kits=(KIT,),
        category=Category.passive,
        summary="Powers the micro:bit away from a computer, through its JST battery socket.",
        aliases=("battery holder", "battery pack", "aa battery"),
        signals=(Signal.none,),
        electrical=Electrical(
            operating_voltage="3 V from two AA cells",
            polarity=Polarity.not_applicable,
            current_notes="Powers the micro:bit through its own battery connector, never into the 3V ring.",
        ),
        teaching=Teaching(safety="Never connect a battery pack to the 3V ring while USB is also plugged in."),
        verification=KEYESTUDIO,
    ),
)
