"""Layer 4 - the modules in the Year 2 kit, Keyestudio KS4010 / KS4009 45-in-1.

Three-pin header modules that plug into the Sensor Shield V2 with female-to-
female Dupont wires. G / V / S ordering on the shield is fixed, so most of the
wiring answer is the same for every module here and lives on the shield's own
profile rather than being repeated forty times.

Several of these are the kit's real teaching hazards and are written up in
detail because of it: the MQ gas sensors draw more current than the micro:bit
can supply, the LM35 wants more supply voltage than the board offers, and the
RGB module is common-anode, which is what started this whole piece of work.

Where Keyestudio's project pages show a wiring photo and working code without
ever stating the active level, the profile says NOT VERIFIED. That is the
honest state, and it is more useful than a plausible guess: the assistant tells
the teacher how to settle it in the classroom in ten seconds instead of handing
them a confident answer that may be backwards.
"""

from __future__ import annotations

from app.services.hardware.schema import (
    Analog,
    Category,
    CodeNotes,
    Component,
    Digital,
    Direction,
    Electrical,
    LedCommon,
    MicrobitNotes,
    Polarity,
    Pwm,
    Signal,
    Teaching,
    Verification,
    Verified,
)

KIT = "KS4010"
DOCS = "https://docs.keyestudio.com/projects/KS4009-KS4010/en/latest/KS4009-KS4010.html"

KEYESTUDIO = Verification(
    status=Verified.manufacturer_doc,
    source="Keyestudio KS4009/KS4010 project documentation",
    source_url=DOCS,
    last_verified="2026-08-30",
)
PART_TYPE = Verification(
    status=Verified.general_knowledge,
    source="Standard behaviour of this part type",
    notes="Confirm against the module before teaching it as fact.",
)
UNCHECKED = Verification(
    status=Verified.needs_verification,
    source="Keyestudio KS4009/KS4010 project pages do not state the active level",
    source_url=DOCS,
    notes="Needs one reading from the physical module to settle.",
)

# The shield fixes the wiring for every module in the kit, so it is stated once.
_SHIELD = "Three-pin cable into one shield group: G to G, V to V, S to the signal pin. Getting G and V the wrong way round destroys the module."

COMPONENTS: tuple[Component, ...] = (
    # ----------------------------------------------------------------- board #
    Component(
        id="ks4010-shield",
        name="micro:bit Sensor Shield V2",
        kits=(KIT,),
        category=Category.breakout,
        summary="The micro:bit slots into this and every module plugs into it. Nothing in this kit connects without it.",
        aliases=("sensor shield", "shield v2", "expansion board", "shield"),
        doc_url=DOCS,
        signals=(Signal.none,),
        electrical=Electrical(
            operating_voltage="3.3 V from the micro:bit, or an external supply on the shield's own input",
            pins=("A G / V / S group per micro:bit pin", "Separate external power input"),
            polarity=Polarity.not_applicable,
            current_notes="On micro:bit power alone the whole shield shares the board's regulator. Anything with a motor, a heater or a coil needs the external input.",
        ),
        microbit=MicrobitNotes(
            wiring="Groups are labelled with the micro:bit's own pin numbers. A module on group P0 is on micro:bit P0, with all of P0's normal rules.",
            conflicts="It exposes P19 and P20 too. They are the I2C bus and are not free general-purpose pins.",
        ),
        teaching=Teaching(
            beginner="A signal router with a shared power rail. It adds no intelligence and no protection.",
            mistakes=(
                "Reading G/V/S in the wrong order. Every cable in this kit is colour-coded to the same order - check it once and keep it.",
                "Expecting the shield to supply motor current from USB alone.",
            ),
            safety="Use the external power input before driving the fan, the servo or an MQ gas sensor.",
        ),
        verification=KEYESTUDIO,
    ),
    # ------------------------------------------------------------------ light #
    Component(
        id="ks4010-rgb-led",
        name="RGB LED Module",
        kits=(KIT,),
        category=Category.light,
        summary="One RGB LED with three colour channels on separate pins. Common-anode, so every channel is active-LOW: 0 lights it and 1 turns it off.",
        aliases=("rgb led module", "rgb led", "rgb module", "rgb", "colour led", "color led"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3 V",
            pins=("R - red channel signal", "G - green channel signal", "B - blue channel signal", "- - GND"),
            signal_channels=3,
            polarity=Polarity.active_low,
            led_common=LedCommon.anode,
            onboard_resistor="One current-limiting resistor per channel, on the module. Never add another.",
        ),
        digital=Digital(
            high_means="That colour channel is OFF. The pin sits at the same potential as the common anode, so no current flows through that colour.",
            low_means="That colour channel is ON. The pin pulls its end of the LED down, so current flows from the common anode through that colour.",
            active_state="LOW",
            inactive_state="HIGH",
            resting_state="All three channels HIGH leaves the LED dark.",
        ),
        pwm=Pwm(
            value_range="0-1023 via analog write",
            increasing_duty="Higher numbers make that channel DIMMER. The channel is active-low, so more time spent HIGH is more time off. 0 is full brightness, 1023 is dark.",
            useful_range="To dim like a normal LED, write 1023 minus the brightness you want.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Three pins, one per colour. P0, P1 and P2 are the usual choice and all support PWM.",
            conflicts="Using P3, P4, P6, P7, P9 or P10 for a colour requires turning the LED display off first.",
            wiring=_SHIELD,
        ),
        makecode=CodeNotes(
            write="pins.digitalWritePin(DigitalPin.P0, 0) lights that channel; ...P0, 1) turns it off. pins.analogWritePin(AnalogPin.P0, 1023) is also off.",
            notes="Not addressable. The NeoPixel extension does not apply - these are three plain pins.",
        ),
        micropython=CodeNotes(
            write="pin0.write_digital(0) lights that channel; pin0.write_digital(1) turns it off. pin0.write_analog(0) is full brightness.",
            notes="Identical electrical behaviour to the MakeCode version. Only the syntax differs.",
        ),
        teaching=Teaching(
            beginner="The three colours share one positive leg, permanently connected to the supply. A colour lights when its own pin pulls the other end down to 0 V. So LOW is on and HIGH is off - for this module.",
            mistakes=(
                "Reading digital write 1 as 'turn on'. On this module it turns the channel off.",
                "Expecting a larger analog value to be brighter. It is dimmer.",
                "Treating it as a NeoPixel and reaching for the strip blocks.",
            ),
            troubleshooting=(
                "White at power-up before any code runs: pins default LOW, so all three channels are on. Set them HIGH first thing in on start.",
                "A colour that never turns off: its pin is tied to GND rather than to the micro:bit.",
            ),
            terms=("common anode", "active-low", "colour channel", "duty cycle"),
        ),
        verification=Verification(
            status=Verified.manufacturer_doc,
            source="Keyestudio KS4009/KS4010 documentation, which states the RGB LED module is common anode",
            source_url=DOCS,
            last_verified="2026-08-30",
            notes="This is the module behind the Grade 7 Lesson 1 correction. Common-anode is a fact about this module, not about RGB LEDs in general.",
        ),
    ),
    Component(
        id="ks4010-white-led",
        name="White LED Module",
        kits=(KIT,),
        category=Category.light,
        summary="A single white LED on one signal pin.",
        aliases=("white led", "digital white led"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="On-board.",
        ),
        digital=Digital(high_means="LED on.", low_means="LED off.", active_state="HIGH", inactive_state="LOW"),
        pwm=Pwm(value_range="0-1023", increasing_duty="Brighter."),
        microbit=MicrobitNotes(suggested_pins="Any PWM-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="The straightforward case: HIGH on, LOW off, because the signal pin drives the LED's positive side.",
            mistakes=("Generalising this to the RGB module in the same kit, which is the opposite.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-red-led",
        name="Red LED Module",
        kits=(KIT,),
        category=Category.light,
        summary="A single red LED, the kit's usual first output and its PWM dimming example.",
        aliases=("red led", "digital red led"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="On-board.",
        ),
        digital=Digital(high_means="LED on.", low_means="LED off.", active_state="HIGH", inactive_state="LOW"),
        pwm=Pwm(
            value_range="0-1023",
            increasing_duty="Brighter. This is the module the kit's breathing-light project uses.",
            useful_range="Perceived brightness is not linear. Half the number is well over half the apparent brightness.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog/PWM pin: P0, P1 or P2.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="The signal pin drives the LED's positive side, so HIGH lights it.",
            terms=("PWM", "duty cycle", "breathing effect"),
        ),
        verification=Verification(
            status=Verified.manufacturer_doc,
            source='Keyestudio documentation: "S pin is for signal control; you can set the High or Low level to control the LED on and off", supply 3.3-5V',
            source_url=DOCS,
            last_verified="2026-08-30",
        ),
    ),
    Component(
        id="ks4010-3w-led",
        name="3W LED Module",
        kits=(KIT,),
        category=Category.light,
        summary="A high-power 3 W LED. Bright enough to need thinking about current.",
        aliases=("3w led", "3 w led", "high power led", "power led"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="On-board driver and resistor.",
            current_notes="The largest steady draw in the kit apart from the motorised parts. Prefer external power on the shield if other modules are also connected.",
        ),
        digital=Digital(high_means="LED on.", low_means="LED off.", active_state="HIGH", inactive_state="LOW"),
        pwm=Pwm(value_range="0-1023", increasing_duty="Brighter."),
        microbit=MicrobitNotes(suggested_pins="Any PWM-capable pin.", wiring=_SHIELD),
        teaching=Teaching(safety="Do not stare into it at full brightness. It gets warm - that is expected, not a fault."),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-traffic-light",
        name="Traffic Light Module",
        kits=(KIT,),
        category=Category.light,
        summary="Red, yellow and green LEDs on one board, one pin each.",
        aliases=("traffic light", "traffic lights"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("R - red", "Y - yellow", "G - green", "GND"),
            signal_channels=3,
            polarity=Polarity.active_high,
            led_common=LedCommon.single,
            onboard_resistor="One per LED.",
        ),
        digital=Digital(high_means="That LED on.", low_means="That LED off.", active_state="HIGH", inactive_state="LOW"),
        microbit=MicrobitNotes(suggested_pins="Three digital pins.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Three separate LEDs. All the sequencing is in the code; the module has no logic.",
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-magic-light-cup",
        name="Magic Light Cup Sensor",
        kits=(KIT,),
        category=Category.light,
        summary="A matched pair of modules, each carrying an LED and a tilt switch, used to make light appear to pour from one cup to the other.",
        aliases=("magic light cup", "light cup"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm, Signal.digital_in),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - LED signal on one module, switch signal on the other", "V - power", "G - GND"),
            signal_channels=2,
            polarity=Polarity.unknown,
            onboard_resistor="On-board for the LED.",
        ),
        digital=Digital(
            high_means="unknown for the tilt half of this pair.",
            low_means="unknown for the tilt half of this pair.",
            active_state="unknown",
            inactive_state="unknown",
        ),
        pwm=Pwm(
            value_range="0-1023 on the LED half",
            increasing_duty="Brighter. The pouring illusion is one LED's value rising while the other's falls.",
        ),
        microbit=MicrobitNotes(suggested_pins="Two pins for the effect: one PWM output per cup.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Two modules, not one. The effect is entirely in the code - the brightness of one is set to the complement of the other.",
            mistakes=("Trying to make it work with a single module.",),
        ),
        verification=UNCHECKED,
    ),
    # ------------------------------------------------------------------ sound #
    Component(
        id="ks4010-active-buzzer",
        name="Active Buzzer Module",
        kits=(KIT,),
        category=Category.sound,
        summary="An ACTIVE buzzer: it contains its own oscillator, so it sounds whenever it is energised. One fixed pitch, not selectable.",
        aliases=("active buzzer", "buzzer module"),
        doc_url=DOCS,
        signals=(Signal.digital_out,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
        ),
        digital=Digital(
            high_means="Buzzer sounds, at its own built-in frequency.",
            low_means="Silent.",
            active_state="HIGH",
            inactive_state="LOW",
        ),
        pwm=Pwm(
            value_range="Analog write works but is nearly pointless here.",
            increasing_duty="Changes loudness a little. It cannot change the pitch - the oscillator is inside the buzzer and its frequency is fixed.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        makecode=CodeNotes(
            write="pins.digitalWritePin(DigitalPin.P0, 1) to sound it, 0 to stop.",
            notes="Do NOT use the music blocks with this one. They send a varying signal, which an active buzzer cannot render as different notes.",
        ),
        micropython=CodeNotes(write="pin0.write_digital(1) sounds it, pin0.write_digital(0) stops it."),
        teaching=Teaching(
            beginner="Active means the oscillator is built in. Give it power and it sounds. That is the whole interface.",
            mistakes=(
                "Trying to play a tune on it. It has one note.",
                "Swapping it with the passive buzzer, which behaves the opposite way round: the passive one needs a changing signal and can play notes; the active one needs a steady level and cannot.",
            ),
            troubleshooting=("Plays every note identically: that is the active buzzer. Use the passive module for melodies.",),
            terms=("active buzzer", "oscillator"),
        ),
        verification=Verification(
            status=Verified.manufacturer_doc,
            source='Keyestudio KS4009/KS4010 Project 17: "an active buzzer has a built-in oscillating source, so it will generate a sound when electrified"',
            source_url=DOCS,
            last_verified="2026-08-30",
        ),
    ),
    Component(
        id="ks4010-passive-buzzer",
        name="Passive Buzzer Module",
        kits=(KIT,),
        category=Category.sound,
        summary="A PASSIVE buzzer: no oscillator inside, so it only makes sound when the signal itself alternates. It can play notes; the active one cannot.",
        aliases=("passive buzzer", "buzzer", "speaker", "melody buzzer"),
        doc_url=DOCS,
        signals=(Signal.pwm, Signal.digital_out),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        digital=Digital(
            high_means="The element is held deflected. Held steady it is silent - at most one click as it moves.",
            low_means="The element is held at rest. Also silent.",
            active_state="No single level activates it. Sound requires the signal to keep changing.",
            inactive_state="Any unchanging level.",
        ),
        pwm=Pwm(
            value_range="Frequency carries the note; duty cycle only affects loudness.",
            increasing_duty="Louder, up to a point. It does not change the pitch.",
            frequency="This is the pitch. Roughly 100 Hz to 5 kHz is useful.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="P0 by default - both MakeCode and MicroPython send music there unless redirected.",
            version_notes="On micro:bit V2 the on-board speaker plays the same music, so a disconnected buzzer can go unnoticed. On V1 silence means check the wiring.",
            wiring=_SHIELD,
        ),
        makecode=CodeNotes(write="music.playTone(...) - the music blocks generate the alternating signal.", notes="A plain digital write produces no tone."),
        micropython=CodeNotes(setup="import music", write="music.pitch(440, 500)"),
        teaching=Teaching(
            beginner="Passive means the micro:bit has to do the oscillating. That is exactly why it can play a melody and the active buzzer cannot.",
            mistakes=("Setting it HIGH and concluding it is faulty.", "Using analog write to change the note - that changes volume, not pitch."),
            terms=("passive buzzer", "frequency", "duty cycle"),
        ),
        verification=Verification(
            status=Verified.manufacturer_doc,
            source="Keyestudio KS4009/KS4010 parts list, which distinguishes the passive from the active buzzer module",
            source_url=DOCS,
            last_verified="2026-08-30",
        ),
    ),
    Component(
        id="ks4010-sound-sensor",
        name="Analog Sound Sensor",
        kits=(KIT,),
        category=Category.sensor_sound,
        summary="A microphone and amplifier read as an analog loudness value.",
        aliases=("sound sensor", "analog sound", "microphone", "noise sensor", "mic"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="Silence does not read 0. There is a resting level and loudness appears as movement above it.",
            calibration="Sample for a few seconds in a quiet room to find the floor, then trigger on the rise above it.",
            environment="Projectors, fans and corridor noise all lift the floor.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="An analog-capable pin: P0, P1, P2, P3, P4 or P10.",
            version_notes="micro:bit V2 has its own microphone; this module is the only option on V1.",
            wiring=_SHIELD,
        ),
        teaching=Teaching(
            beginner="Each read catches the waveform at one instant, so a single sample is nearly meaningless. Read repeatedly and take the peak.",
            mistakes=("Expecting silence to read zero.", "Taking one sample and calling it the noise level."),
        ),
        verification=PART_TYPE,
    ),
    # ------------------------------------------------------ motion / switching #
    Component(
        id="ks4010-servo",
        name="Micro Servo",
        kits=(KIT,),
        category=Category.motion,
        summary="A small positional servo. Its angle is set by the WIDTH of a pulse, not by a voltage or a duty percentage.",
        aliases=("servo", "micro servo", "sg90", "servo motor"),
        doc_url=DOCS,
        signals=(Signal.pwm,),
        electrical=Electrical(
            operating_voltage="4.8-6 V for the motor. The signal line is happy at 3.3 V.",
            pins=("Orange/yellow - signal", "Red - power", "Brown/black - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            current_notes="Draws a large surge when it starts moving and much more again if it is held against a stop. This is more than the micro:bit's 3V regulator can give: power it from the shield's external input.",
        ),
        pwm=Pwm(
            value_range="0-180 degrees, through the servo blocks. Underneath it is a pulse roughly 0.5-2.5 ms long, repeated every 20 ms.",
            increasing_duty="A longer pulse means a larger angle. Do not think about it as duty percentage - the servo measures the pulse width and ignores the rest of the period.",
            frequency="About 50 Hz. Changing the frequency breaks it.",
            useful_range="Stay a little inside 0 and 180. At the extremes many servos buzz against an internal stop and overheat.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any PWM-capable pin. P0, P1 and P2 are the usual choices.",
            conflicts="Servo PWM and buzzer tones on the same pin fight each other.",
            wiring="Signal into the shield's S, but take power from the external supply, not the micro:bit, with grounds joined.",
        ),
        makecode=CodeNotes(write="pins.servoWritePin(AnalogPin.P0, 90) centres it. The block handles the pulse timing."),
        micropython=CodeNotes(
            setup="pin0.set_analog_period(20) sets the 20 ms frame first.",
            write="pin0.write_analog(...) with a value that gives the right pulse width. Less forgiving than MakeCode - the block does this arithmetic for you.",
        ),
        teaching=Teaching(
            beginner="It is not a motor you turn on. You tell it an angle and it holds there, correcting itself continuously - which is why it keeps drawing current while it is 'still'.",
            mistakes=(
                "Powering it from the micro:bit. The board browns out and resets, and the fault looks like a code bug.",
                "Forgetting to join grounds when using external power.",
                "Reading its pulse as a normal PWM brightness value.",
            ),
            troubleshooting=(
                "micro:bit resets when the servo moves: it is being powered from the board. Move it to external power.",
                "Buzzing and getting hot without moving: commanded past its mechanical limit.",
            ),
            safety="Never hold the horn still while it is powered.",
            terms=("pulse width", "50 Hz frame", "stall current"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-fan",
        name="Fan Module",
        kits=(KIT,),
        category=Category.motion,
        summary="A small DC motor and fan with a driver transistor on the module, so it can be switched from one pin.",
        aliases=("fan module", "fan", "motor fan"),
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.pwm),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            current_notes="A motor. Even with the on-board driver, the current comes from V, not from the signal pin - use the shield's external power.",
        ),
        digital=Digital(high_means="Fan runs.", low_means="Fan stops.", active_state="HIGH", inactive_state="LOW"),
        pwm=Pwm(
            value_range="0-1023",
            increasing_duty="Faster.",
            useful_range="Below roughly a third of full scale most small motors will not start turning at all, though they will keep turning if already moving.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any PWM-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="The driver on the module is what makes this safe from one pin. A bare motor is not - the pin cannot supply motor current and the motor's collapsing field would damage it.",
            mistakes=("Concluding from this module that a motor can be wired straight to a pin. It cannot; the module has the driver.",),
            troubleshooting=("Twitches and the micro:bit resets: powered from the board rather than externally.",),
            safety="Keep fingers and hair clear. Do not stall the blade.",
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-relay",
        name="Single Relay Module",
        kits=(KIT,),
        category=Category.switching,
        summary="An electrically operated switch: a small signal closes contacts that can carry a separate circuit.",
        aliases=("relay", "relay module", "single relay"),
        doc_url=DOCS,
        signals=(Signal.digital_out,),
        electrical=Electrical(
            operating_voltage="Coil and driver typically want 5 V; the signal line is fine at 3.3 V.",
            pins=("S - signal", "V - power", "G - GND", "Screw terminals: COM, NO, NC on the switched side"),
            signal_channels=1,
            polarity=Polarity.active_high,
            current_notes="The coil draws steadily while energised. Use external power on the shield.",
        ),
        digital=Digital(
            high_means="Coil energised: COM connects to NO, and disconnects from NC. The click is the armature moving.",
            low_means="Coil released: COM connects back to NC.",
            active_state="HIGH",
            inactive_state="LOW",
            resting_state="Unpowered, COM is connected to NC. That is what normally-closed means, and it is why a relay's default state matters for safety.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Two completely separate circuits sharing one part: a coil the micro:bit controls, and a set of contacts that touch nothing electrical on the micro:bit side. That isolation is the point of a relay.",
            mistakes=(
                "Thinking the switched side is powered by the micro:bit. It is not - it is a bare switch and needs its own circuit.",
                "Not noticing that NC is connected when everything is off.",
            ),
            troubleshooting=("Clicks but the load does nothing: the load circuit is on the wrong terminal pair, or has no supply of its own.",),
            safety="In a classroom this switches low-voltage loads only - a lamp on a battery, a second motor circuit. Never mains. If a lesson shows it switching a wall outlet, that lesson is not for a classroom bench.",
            terms=("COM", "normally open", "normally closed", "isolation"),
        ),
        verification=PART_TYPE,
    ),
    # ---------------------------------------------------------- manual inputs #
    Component(
        id="ks4010-push-button",
        name="Digital Push Button",
        kits=(KIT,),
        category=Category.input_control,
        summary="A momentary push button module. Which level it reads when pressed is not documented.",
        aliases=("push button", "digital push button", "button module", "button"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
            pull_resistor="On the module; its direction is unconfirmed.",
        ),
        digital=Digital(
            high_means="unknown for this module.",
            low_means="unknown for this module.",
            active_state="unknown",
            inactive_state="unknown",
            resting_state="Held stable by the module's pull resistor, not floating.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin except P5 and P11, which are buttons A and B.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="A switch plus a resistor. The resistor sets what the pin reads when nothing is pressed, and that decides whether pressed is 0 or 1.",
            troubleshooting=("Show the pin value on the display and press it once. Whatever it changes to is this module's pressed level.",),
            mistakes=("Assuming it matches micro:bit buttons A and B, which read LOW when pressed.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-joystick",
        name="Joystick Module",
        kits=(KIT,),
        category=Category.input_control,
        summary="Two-axis thumbstick with a push switch: two analog outputs and one digital.",
        aliases=("joystick", "thumbstick", "stick"),
        doc_url=DOCS,
        signals=(Signal.analog_in, Signal.digital_in),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("X - analog", "Y - analog", "B - digital button", "V - power", "G - GND"),
            signal_channels=3,
            polarity=Polarity.unknown,
        ),
        analog=Analog(
            raw_range="0-1023 per axis",
            direction=Direction.more_is_higher,
            typical_values="Rest is near mid-scale, around 500, and almost never exactly 512.",
            calibration="Record the resting value and use a dead band around it.",
        ),
        digital=Digital(high_means="unknown for this module's button.", low_means="unknown.", active_state="unknown", inactive_state="unknown"),
        microbit=MicrobitNotes(
            suggested_pins="Two analog-capable pins plus one digital - three pins in total.",
            conflicts="Only six pins can read analog, and two of them are needed here.",
            wiring=_SHIELD,
        ),
        teaching=Teaching(
            beginner="Two potentiometers at right angles and a button. Nothing conceptually new.",
            mistakes=("Assuming centre is exactly 512.", "Omitting the dead band, so the robot creeps when the stick is released."),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-rotation",
        name="Analog Rotation Sensor",
        kits=(KIT,),
        category=Category.input_control,
        summary="A potentiometer knob read as an analog value. The kit's clearest analog input.",
        aliases=("rotation sensor", "analog rotation", "potentiometer", "knob", "pot", "dial"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            minimum="Near 0 at one end stop.",
            maximum="Near 1023 at the other.",
            calibration="Read both end stops and map from what it actually reaches.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin: P0, P1, P2, P3, P4 or P10.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="A voltage divider you turn by hand. The wiper picks off a fraction of the supply and the micro:bit converts it to 0-1023.",
            terms=("voltage divider", "wiper", "map"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-touch",
        name="Capacitive Touch Sensor",
        kits=(KIT,),
        category=Category.sensor_touch,
        summary="A capacitive touch pad, typically a TTP223, with no moving parts.",
        aliases=("capacitive touch", "touch sensor", "touch module", "touch pad"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
        ),
        digital=Digital(
            high_means="Touched.",
            low_means="Not touched.",
            active_state="HIGH",
            inactive_state="LOW",
            triggered_state="HIGH while a finger is on the pad, in the chip's default mode.",
            resting_state="LOW",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", version_notes="Separate from the micro:bit V2 touch logo.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="It senses the capacitance a finger adds, so it works through paper or a thin sticker but not through metal.",
            troubleshooting=("Triggering by itself: the module is resting on something conductive, or the supply is noisy.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-crash",
        name="Crash Sensor",
        kits=(KIT,),
        category=Category.sensor_touch,
        summary="A lever microswitch used as a bumper. Its output level is not documented.",
        aliases=("crash sensor", "collision sensor", "limit switch", "bumper", "microswitch"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(
            high_means="unknown for this module.",
            low_means="unknown for this module.",
            active_state="unknown",
            inactive_state="unknown",
            triggered_state="The lever pressed in. Which level that gives is unconfirmed.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Mechanically the same idea as a push button, packaged with a long lever so a robot chassis can trip it.",
            troubleshooting=("Press the lever with the value on the display to find the pressed level.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-tilt",
        name="Digital Tilt Sensor",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="A ball-in-tube switch that changes state when tipped past an angle. Output level not documented.",
        aliases=("tilt sensor", "digital tilt", "tilt switch"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(high_means="unknown.", low_means="unknown.", active_state="unknown", inactive_state="unknown"),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", conflicts="The micro:bit's own accelerometer gives a real angle; this gives one bit.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="One bit: tipped or not. There is no angle in it.",
            mistakes=("Expecting a measurement. For an angle, use the micro:bit's accelerometer instead.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-vibration",
        name="Vibration Sensor",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="A spring or ball switch that closes briefly when shaken. Output level not documented.",
        aliases=("vibration sensor", "shake sensor", "vibration module"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(
            high_means="unknown.",
            low_means="unknown.",
            active_state="unknown",
            inactive_state="unknown",
            triggered_state="A brief contact while shaking - often only a few milliseconds.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="It closes for an instant, not for as long as the shaking lasts. A slow loop misses it entirely.",
            mistakes=("Polling once a second and concluding the sensor is dead.",),
            troubleshooting=("Read in a tight loop, or latch the event in a variable and clear it after acting.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-knock",
        name="Knock Sensor Module",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="Responds to a tap or knock on its surface. Output level not documented.",
        aliases=("knock sensor", "tap sensor", "impact sensor"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(high_means="unknown.", low_means="unknown.", active_state="unknown", inactive_state="unknown", triggered_state="A brief pulse on impact."),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(beginner="Like the vibration sensor: a very short event that a slow loop will miss."),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-reed",
        name="Reed Switch Module",
        kits=(KIT,),
        category=Category.sensor_magnetic,
        summary="Two contacts sealed in glass that close near a magnet. Output level not documented.",
        aliases=("reed switch", "reed sensor", "magnetic switch"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(high_means="unknown.", low_means="unknown.", active_state="unknown", inactive_state="unknown", triggered_state="A magnet brought close."),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="A genuinely mechanical switch operated by a magnetic field - this is what a door alarm uses.",
            mistakes=("Confusing it with the Hall sensor. A reed switch has moving contacts; a Hall sensor is solid state.",),
            troubleshooting=("Bring a magnet up with the value on the display to find its triggered level.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-hall",
        name="Hall Magnetic Sensor",
        kits=(KIT,),
        category=Category.sensor_magnetic,
        summary="Solid-state magnetic field detector. Hall modules come in both polarities and this one is not documented.",
        aliases=("hall sensor", "hall magnetic", "magnet sensor", "magnetic sensor"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(
            high_means="unknown for this module.",
            low_means="unknown for this module.",
            active_state="unknown",
            inactive_state="unknown",
            triggered_state="A magnet close by. Many Hall switches are open-drain and pull LOW when triggered, but that is not confirmed here.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="No moving parts, so it lasts far longer than a reed switch and reacts faster.",
            mistakes=("Not realising many Hall switches respond to only one magnetic pole. Turn the magnet over before declaring it broken.",),
        ),
        verification=UNCHECKED,
    ),
    # ----------------------------------------------------------- optical input #
    Component(
        id="ks4010-ir-obstacle",
        name="Infrared Obstacle Detector Sensor",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="Shines infrared and watches for a reflection. Modules of this type usually pull the output LOW when something is in front.",
        aliases=("infrared obstacle", "ir obstacle", "obstacle sensor", "obstacle avoidance", "proximity sensor"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - digital signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_low,
            potentiometer="The trimmer sets the comparator threshold - effectively the detection DISTANCE. It does not change what the sensor can physically see.",
        ),
        digital=Digital(
            high_means="Nothing detected. This is the idle state.",
            low_means="An obstacle is reflecting infrared back.",
            active_state="LOW",
            inactive_state="HIGH",
            triggered_state="LOW",
            resting_state="HIGH",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="A good example of why 0 and 1 have no universal meaning: on this module 0 is 'something is there', while on the touch sensor next to it 0 means 'nothing is happening'. The sensor decides, not the number.",
            mistakes=(
                "Reading 0 as 'clear'. It is the opposite here.",
                "Believing the trimmer changes the sensor's range. It changes the threshold at which the comparator flips.",
            ),
            troubleshooting=(
                "Never detects anything: black or matt surfaces absorb infrared. Try a white card.",
                "Always detects: sunlight, or the trimmer wound too far.",
            ),
            terms=("active-low", "comparator", "threshold"),
        ),
        verification=Verification(
            status=Verified.general_knowledge,
            source="Standard behaviour of infrared obstacle modules of this type; Keyestudio's page does not state the level",
            source_url=DOCS,
            notes="High confidence for the part type. Confirm on the module before teaching it as certain.",
        ),
    ),
    Component(
        id="ks4010-line-tracking",
        name="Line Tracking Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="An infrared reflectance sensor for following a line. Which surface gives which level is not documented and differs between makes.",
        aliases=("line tracking", "line follower", "line sensor", "tracking sensor", "tcrt5000"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - digital signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
            potentiometer="Sets the comparator threshold - how dark counts as 'the line'.",
        ),
        digital=Digital(
            high_means="unknown for this module - it is black on some makes and white on others.",
            low_means="unknown for this module.",
            active_state="unknown",
            inactive_state="unknown",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="It measures how much infrared bounces back. White reflects, black absorbs. Whether the module reports the reflective case as 1 or as 0 is a design choice of the board.",
            troubleshooting=(
                "Settle it in ten seconds: display the value, then move the sensor from white paper to a black line. Whichever way it flips is the answer for this module.",
                "Never changes: adjust the trimmer, and hold the sensor a few millimetres above the surface rather than touching it.",
            ),
            mistakes=("Copying a threshold or a polarity from a different robot kit.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-photo-interrupter",
        name="Photo Interrupter Module",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="An infrared beam across a slot; the output changes when something breaks it. Output level not documented.",
        aliases=("photo interrupter", "photointerrupter", "slot sensor", "beam sensor", "optical switch"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - digital signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.unknown,
        ),
        digital=Digital(high_means="unknown.", low_means="unknown.", active_state="unknown", inactive_state="unknown", triggered_state="Something in the slot blocking the beam."),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="An emitter facing a detector across a gap. Counting slots in a spinning disc is what turns this into a speed sensor.",
            troubleshooting=("Pass a card through the slot with the value on the display to find its blocked level.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-ir-receiver",
        name="Digital IR Receiver Module",
        kits=(KIT,),
        category=Category.communication,
        summary="Receives the coded infrared bursts from a remote control. Its pin carries a protocol, not a simple on/off level.",
        aliases=("ir receiver", "infrared receiver", "remote receiver", "vs1838"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_low,
        ),
        digital=Digital(
            high_means="Idle - no infrared carrier being received. The line rests HIGH.",
            low_means="Carrier detected. The bursts of LOW are the data, not a state you should read as a single value.",
            active_state="LOW pulses",
            inactive_state="HIGH",
            resting_state="HIGH",
            triggered_state="A rapid train of LOW pulses whose TIMING encodes the button. Reading this pin with a plain digital read tells you almost nothing - a decoder is required.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any digital pin, chosen to match what the decoding extension expects.",
            conflicts="Decoding is timing-critical, so heavy work elsewhere in the loop can cause missed buttons.",
            wiring=_SHIELD,
        ),
        makecode=CodeNotes(extension="Needs an infrared receiver extension. There is no built-in block for it.", read="The extension raises an event carrying the button code."),
        micropython=CodeNotes(notes="No built-in decoder. It needs a driver supplied with the lesson."),
        teaching=Teaching(
            beginner="The clearest case in the kit where reading the pin as 0 or 1 is meaningless. The information is in the pattern over time, which is why an extension is needed.",
            mistakes=("Reading it with digital read and expecting a button number.",),
            terms=("carrier", "protocol", "decoder"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-ir-remote",
        name="IR Remote Control",
        kits=(KIT,),
        category=Category.passive,
        summary="The handset that the IR receiver module listens to. Battery powered, nothing to wire.",
        aliases=("ir remote", "remote control", "infrared remote", "handset"),
        doc_url=DOCS,
        signals=(Signal.none,),
        electrical=Electrical(operating_voltage="Its own coin cell", polarity=Polarity.not_applicable),
        teaching=Teaching(
            troubleshooting=("Nothing received: the plastic tab is usually still under the battery on a new kit. Point it at the receiver - infrared does not go round corners.",),
        ),
        verification=KEYESTUDIO,
    ),
    # ------------------------------------------------------ environment sensing #
    Component(
        id="ks4010-ultrasonic",
        name="Ultrasonic Module",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="Measures distance by timing an ultrasonic echo. Two pins: one to send the ping, one that reports how long it took.",
        aliases=("ultrasonic", "ultrasonic sensor", "distance sensor", "hc-sr04", "sonar"),
        model="HC-SR04 type",
        doc_url=DOCS,
        signals=(Signal.digital_out, Signal.digital_in),
        electrical=Electrical(
            operating_voltage="Modules of this type usually want 5 V. Take V from the shield rather than assuming 3.3 V will do.",
            pins=("Trig - input, the micro:bit drives this", "Echo - output, the micro:bit measures this", "V - power", "G - GND"),
            signal_channels=2,
            polarity=Polarity.not_applicable,
        ),
        digital=Digital(
            high_means="On Echo: the pulse is still running. Its WIDTH is the measurement - a longer HIGH means a more distant object.",
            low_means="On Echo: idle, between measurements.",
            active_state="A HIGH pulse on Echo whose duration is the answer",
            inactive_state="LOW",
            triggered_state="The micro:bit sends a short HIGH on Trig, and the module answers with a timed pulse on Echo.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Two digital pins, one for Trig and one for Echo.",
            version_notes="If the module is running at 5 V, its Echo output can exceed the micro:bit's 3.3 V limit. Check what voltage the shield is feeding it before wiring Echo straight to a pin.",
            wiring="Four connections: Trig, Echo, V and G. Trig and Echo are not interchangeable.",
        ),
        makecode=CodeNotes(extension="Usually an ultrasonic extension, which does the ping-and-time sequence and returns centimetres."),
        micropython=CodeNotes(notes="Needs manual pulse timing, or a driver from the lesson. Considerably harder than the MakeCode block."),
        teaching=Teaching(
            beginner="It is a stopwatch, not a ruler. Sound goes out, bounces, comes back; the module reports the round trip and the code turns time into distance.",
            mistakes=(
                "Swapping Trig and Echo. Nothing is damaged, nothing works.",
                "Expecting it to see a soft or angled surface. Cloth absorbs the pulse and a slanted wall deflects it away.",
            ),
            troubleshooting=("Always reads maximum: nothing is coming back. Try a flat surface square to the sensor.",),
            terms=("Trig", "Echo", "pulse width", "time of flight"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-dht11",
        name="Temperature and Humidity Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="A combined temperature and humidity sensor, typically a DHT11, that speaks its own single-wire protocol.",
        aliases=("temperature and humidity", "dht11", "dht", "humidity sensor"),
        model="DHT11 type",
        doc_url=DOCS,
        signals=(Signal.digital_in, Signal.digital_out),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - bidirectional data", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            pull_resistor="Needs a pull-up on the data line; on this module it is fitted.",
        ),
        digital=Digital(
            high_means="Idle. The data line rests HIGH between exchanges.",
            low_means="Part of a timed exchange, not a state to read.",
            active_state="Not a level. Both sides take turns driving the same wire to a strict timing.",
            inactive_state="HIGH",
            triggered_state="A digital read on this pin returns a bit of a protocol frame, never a temperature. It needs a driver.",
        ),
        analog=Analog(
            raw_range="Not analog. The sensor returns whole degrees Celsius and whole percent relative humidity through the protocol.",
            direction=Direction.not_applicable,
            typical_values="Roughly 0-50 C and 20-90 % RH for a DHT11, to about one degree and a few percent.",
            calibration="Factory calibrated. Nothing to trim.",
            environment="It reads its own local air. Leave it a minute after a move, and keep it away from the micro:bit's own warmth.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any digital pin; match what the extension expects.",
            conflicts="Do not read it more than about once a second - the sensor itself needs the gap.",
            wiring=_SHIELD,
        ),
        makecode=CodeNotes(extension="Needs a DHT11 extension. Without it there are no blocks for this sensor.", read="Extension blocks return temperature and humidity separately."),
        micropython=CodeNotes(notes="No built-in driver; needs one from the lesson."),
        teaching=Teaching(
            beginner="One wire carrying a conversation, not a level. That is why it needs an extension when the photocell next to it needs nothing.",
            mistakes=("Using analog read on it and getting a meaningless number.", "Polling it in a tight loop and getting errors."),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-ds18b20",
        name="18B20 Temperature Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="A DS18B20 digital thermometer on the 1-Wire bus. Accurate, and needs a driver rather than an analog read.",
        aliases=("18b20", "ds18b20", "digital temperature", "one wire temperature"),
        model="DS18B20",
        doc_url=DOCS,
        signals=(Signal.one_wire,),
        electrical=Electrical(
            operating_voltage="3.0-5.5 V",
            pins=("S - 1-Wire data", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            pull_resistor="1-Wire needs a pull-up on the data line; the module carries it.",
        ),
        analog=Analog(
            raw_range="Not analog. It returns degrees Celsius directly over the bus.",
            direction=Direction.not_applicable,
            typical_values="About -55 to +125 C, to a fraction of a degree.",
            calibration="Factory calibrated.",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin the driver supports.", wiring=_SHIELD),
        makecode=CodeNotes(extension="Needs a DS18B20 / 1-Wire extension."),
        micropython=CodeNotes(notes="Needs a 1-Wire driver from the lesson."),
        teaching=Teaching(
            beginner="Compare it with the analog temperature sensor in the same kit: this one does the converting itself and sends a number, so nothing has to be mapped or calibrated.",
            mistakes=("Reading it with analog read. It has no analog output.",),
            terms=("1-Wire", "digital sensor", "bus"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-analog-temperature",
        name="Analog Temperature Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="A thermistor in a divider, read as an analog value. Which way the number moves with temperature is not documented.",
        aliases=("analog temperature", "thermistor", "temperature sensor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.unknown,
            calibration="Read it at room temperature, then pinch the thermistor between your fingers. If the number rises, warmer means higher on this module; if it falls, the opposite.",
            typical_values="A thermistor is not linear. Turning the raw value into degrees needs the Steinhart-Hart equation or a lookup table, which is why this is a harder sensor than the DS18B20 next to it.",
            environment="It measures its own body temperature, so airflow and nearby warm components shift it.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="A resistor whose value changes with heat. The micro:bit reads a voltage, not a temperature - the conversion is the lesson.",
            mistakes=(
                "Assuming a bigger number means hotter without checking.",
                "Mapping it linearly to degrees. It is not linear, so a straight-line map is only roughly right near the middle.",
            ),
            terms=("thermistor", "NTC", "non-linear", "voltage divider"),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-lm35",
        name="LM35 Linear Temperature Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="A linear temperature sensor whose output rises 10 mV per degree Celsius. Its supply requirement is worth checking on a 3.3 V board.",
        aliases=("lm35", "linear temperature", "lm35 sensor"),
        model="LM35",
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="The LM35 datasheet specifies a minimum supply of 4 V. The micro:bit's 3V rail is below that, so power it from the shield's 5 V supply and check the reading against a known temperature before trusting it.",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            current_notes="Tiny. Supply voltage, not current, is the constraint here.",
        ),
        analog=Analog(
            raw_range="0-1023 on the micro:bit",
            direction=Direction.more_is_higher,
            typical_values="10 mV per degree C. Against a 3.3 V reference each ADC step is about 3.2 mV, so one raw count is roughly a third of a degree, and room temperature lands around 70-80 raw.",
            calibration="Linear, unlike the thermistor: degrees are (raw / 1023) * 3300 / 10.",
            environment="Reads its own body temperature.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="An analog-capable pin.",
            version_notes="If it is powered at 5 V, confirm its output stays under 3.3 V - it will, at any classroom temperature, since 3.3 V would mean 330 C.",
            wiring=_SHIELD,
        ),
        teaching=Teaching(
            beginner="The easy one to convert: millivolts straight to degrees, no curve and no lookup table. Compare it with the thermistor to show why linear sensors are worth more.",
            mistakes=("Powering it from the micro:bit's 3V and treating the reading as correct. It is out of the part's stated supply range there.",),
            terms=("linear", "millivolts per degree", "reference voltage"),
        ),
        verification=Verification(
            status=Verified.general_knowledge,
            source="LM35 datasheet behaviour (10 mV/C, 4 V minimum supply). Keyestudio's page does not state the module's supply arrangement",
            source_url=DOCS,
            notes="Worth confirming how this specific module is powered on the shield.",
        ),
    ),
    Component(
        id="ks4010-photocell",
        name="Photocell Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="A light-dependent resistor read as an analog value. The direction of the reading is not documented.",
        aliases=("photocell", "photoresistor", "ldr", "light sensor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.unknown,
            calibration="Display the reading and cup your hand over it. If the number falls, brighter means higher on this module; if it rises, the opposite.",
            environment="Windows, ceiling lights and time of day all shift it, so thresholds do not transfer between rooms.",
            threshold="Set it from a bright reading and a covered reading taken in the actual classroom.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin: P0, P1, P2, P3, P4 or P10.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Its resistance drops as light rises. Whether the NUMBER goes up or down depends on which half of the divider the micro:bit reads - a property of the module, not of light.",
            mistakes=("Assuming higher always means brighter.", "Reusing a threshold from another room."),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-ambient-light",
        name="Ambient Light Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="A phototransistor light sensor, closer to eye response and faster than a photocell.",
        aliases=("ambient light", "ambient light sensor", "temt6000"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            calibration="Confirm with the cover-it test before relying on it in a lesson.",
            environment="Tracks visible light much as an eye does.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="More light lets more current through the phototransistor, raising the voltage the micro:bit reads.",
            mistakes=("Treating it as interchangeable with the photocell. Different spectrum, different speed.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-uv",
        name="Ultraviolet Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="Measures ultraviolet intensity as an analog value.",
        aliases=("ultraviolet sensor", "uv sensor", "uv"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="Near zero indoors. It needs sunlight or a UV source to read anything at all.",
            calibration="The raw value is not a UV index. Converting to one would need a reference this kit does not include.",
            environment="Ordinary window glass blocks most UVB, so a reading taken indoors by a window is not a reading of what is outside.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="It sees the part of sunlight your eyes cannot. Indoors it reads nothing, which is the point rather than a fault.",
            mistakes=("Calling the raw number a UV index.", "Testing it under classroom lighting and concluding it is broken."),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-flame",
        name="Flame Sensor",
        kits=(KIT,),
        category=Category.sensor_light,
        summary="An infrared photodiode aimed at the wavelengths a flame emits. Direction of the reading not documented.",
        aliases=("flame sensor", "fire sensor", "flame detector"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.unknown,
            calibration="Take a baseline in the room, then hold a lighter at a safe distance and note which way the number moves. That is the direction for this module.",
            threshold="Set it above the room's own infrared baseline, which is not zero.",
            environment="Sunlight and incandescent bulbs emit in the same band and will trigger it.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="It detects the infrared a flame gives off, not heat and not smoke. A hot radiator does not register; a sunbeam might.",
            mistakes=("Calling it a fire alarm. It is a short-range infrared detector.",),
            safety="Naked flames in a classroom need the school's own risk assessment. A warm soldering iron or a torch bulb demonstrates it without one.",
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-steam",
        name="Steam Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="Interlocking traces that read the conductivity of moisture landing on them - water droplets or steam.",
        aliases=("steam sensor", "rain sensor", "water sensor", "moisture sensor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="Dry sits near the bottom of the range. A drop of water lifts it sharply.",
            calibration="Record dry, then a wetted fingertip, and set the threshold between them.",
            environment="Tap water conducts better than distilled, so the same wetness reads differently with different water.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Moisture bridges the traces and lets a little current across. More bridging means a higher reading.",
            mistakes=("Submerging the connector end. Only the traced area is meant to get wet.",),
            troubleshooting=("Drifts upward over time: leave it powered only while reading, or the traces corrode.",),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-water-level",
        name="Water Level Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="A ladder of parallel traces: the deeper the water, the more of them are bridged, and the higher the reading.",
        aliases=("water level", "water level sensor", "liquid level"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="Dry near the bottom of the range, rising in rough steps as each trace goes under.",
            calibration="Dip it to a few marked depths and record the readings. It is not linear and it is not calibrated in millimetres.",
            environment="Depends on what is dissolved in the water. Salt water reads far higher than distilled at the same depth.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Depth becomes conductivity: the more traces the water covers, the easier the current path, the higher the number.",
            mistakes=("Letting the water reach the header pins. Only the traced strip goes in.", "Expecting a depth in millimetres straight out of it."),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-soil",
        name="Soil Humidity Sensor",
        kits=(KIT,),
        category=Category.sensor_environment,
        summary="Two probes reading the conductivity of the soil between them. Direction of the reading not documented.",
        aliases=("soil humidity", "soil moisture", "soil sensor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.unknown,
            calibration="Two readings settle it and belong in the lesson: probes in air, and probes in a glass of water. Everything else lies between them, and which end is the larger number is a property of this module.",
            environment="Fertiliser and mineral content change conductivity, so the same wetness reads differently in different soil.",
            threshold="From the calibration readings, never from a worksheet number.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Wet soil conducts better than dry soil. That is the entire principle - everything else is mapping.",
            mistakes=("Assuming higher means wetter.", "Reporting the raw value as a percentage."),
            troubleshooting=("Readings drift over weeks: the probes corrode under constant power. Power it only while reading.",),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-pressure",
        name="Thin-film Pressure Sensor",
        kits=(KIT,),
        category=Category.sensor_touch,
        summary="A force-sensing resistor: pressing it changes its resistance. Direction of the reading not documented.",
        aliases=("thin film pressure", "pressure sensor", "force sensor", "fsr", "force sensitive resistor"),
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.unknown,
            calibration="Read it untouched, then press hard, and note which way it moves.",
            typical_values="Strongly non-linear: light pressure moves it a lot, and beyond a moderate force it barely changes. It ranks pressure well and measures it badly.",
            environment="Where on the pad you press changes the reading as much as how hard.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Pressing squeezes conductive layers together, so more contact means less resistance. Good for 'is it being pressed, and roughly how hard', not for weighing anything.",
            mistakes=("Using it as a scale.", "Bending or creasing the film, which damages it permanently."),
        ),
        verification=UNCHECKED,
    ),
    Component(
        id="ks4010-gas",
        name="Analog Gas Sensor",
        kits=(KIT,),
        category=Category.sensor_gas,
        summary="An MQ-type gas sensor with a heated element. It draws real current and needs several minutes to warm up.",
        aliases=("gas sensor", "analog gas", "mq2", "mq-2", "smoke sensor"),
        model="MQ-2 type",
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="5 V for the heater. It will not read correctly on 3.3 V.",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            current_notes="The internal heater draws on the order of a hundred milliamps, continuously. That is comparable to the micro:bit's entire 3V budget, so use the shield's external supply - not USB through the board.",
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="Never zero. There is a substantial baseline in clean air, and the useful signal is the rise above it.",
            calibration="Needs several minutes of warm-up before the baseline settles, and a fresh sensor needs far longer. Take the baseline after warm-up, every session.",
            environment="It responds to a family of gases rather than one, so it cannot say WHICH gas. Humidity and temperature move the baseline too.",
            threshold="Relative to that session's baseline, never an absolute number.",
        ),
        microbit=MicrobitNotes(
            suggested_pins="An analog-capable pin.",
            conflicts="If the micro:bit browns out or resets when this is connected, it is being asked to supply the heater.",
            wiring="Signal to the shield; power from the external supply, grounds joined.",
        ),
        teaching=Teaching(
            beginner="A heated sensing surface whose resistance changes when certain gases touch it. The heater is why it gets warm and why it cannot run off the micro:bit.",
            mistakes=(
                "Reading it immediately after power-up.",
                "Claiming it identifies a specific gas.",
                "Powering it from the micro:bit and blaming the code for the resets.",
            ),
            safety="Demonstrate with a puff of breath or a marker pen, never with a butane canister. It gets hot in normal use - that is expected.",
            terms=("baseline", "warm-up", "heater"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-alcohol",
        name="Analog Alcohol Sensor",
        kits=(KIT,),
        category=Category.sensor_gas,
        summary="An MQ-3 type alcohol vapour sensor. Same heated construction and same current and warm-up caveats as the gas sensor.",
        aliases=("alcohol sensor", "analog alcohol", "mq3", "mq-3", "breathalyser", "breathalyzer"),
        model="MQ-3 type",
        doc_url=DOCS,
        signals=(Signal.analog_in,),
        electrical=Electrical(
            operating_voltage="5 V for the heater.",
            pins=("S - analog signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.not_applicable,
            current_notes="Heated element, on the order of a hundred milliamps continuously. Use the shield's external supply.",
        ),
        analog=Analog(
            raw_range="0-1023",
            direction=Direction.more_is_higher,
            typical_values="A substantial baseline in clean air; the signal is the rise above it.",
            calibration="Several minutes of warm-up before the baseline settles. Re-baseline every session.",
            environment="Responds to other vapours as well - hand sanitiser and marker pens both set it off.",
        ),
        microbit=MicrobitNotes(suggested_pins="An analog-capable pin.", wiring="Signal to the shield; power externally, grounds joined."),
        teaching=Teaching(
            beginner="Same heated-surface principle as the gas sensor, tuned to alcohol vapour.",
            mistakes=("Presenting it as a breathalyser. It gives an uncalibrated relative number and says nothing about blood alcohol.",),
            safety="Demonstrate with hand sanitiser on a cotton bud. There is no reason to bring alcohol into the classroom for it.",
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-pir",
        name="PIR Motion Sensor",
        kits=(KIT,),
        category=Category.sensor_motion,
        summary="Passive infrared motion detector: it senses a warm body moving across its view.",
        aliases=("pir", "pir motion", "motion sensor", "movement sensor"),
        doc_url=DOCS,
        signals=(Signal.digital_in,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("S - signal", "V - power", "G - GND"),
            signal_channels=1,
            polarity=Polarity.active_high,
            potentiometer="Where trimmers are fitted they set sensitivity and how long the output stays HIGH after a trigger, not the detection principle.",
        ),
        digital=Digital(
            high_means="Motion detected, and it holds HIGH for a short time after the movement stops.",
            low_means="No motion within the hold window.",
            active_state="HIGH",
            inactive_state="LOW",
            triggered_state="HIGH",
            resting_state="LOW",
        ),
        microbit=MicrobitNotes(suggested_pins="Any digital pin.", wiring=_SHIELD),
        teaching=Teaching(
            beginner="Passive: it emits nothing, it only notices infrared changing. It detects MOVEMENT, so a person sitting still vanishes from it.",
            mistakes=("Expecting it to see someone present but motionless.", "Testing it in the first minute after power-up."),
            troubleshooting=(
                "Stuck HIGH just after power-on is normal warm-up. Wait up to a minute.",
                "Triggering at nothing: it also sees a radiator, a draught, or sunlight moving across the room.",
            ),
            terms=("passive infrared", "hold time"),
        ),
        verification=PART_TYPE,
    ),
    # ----------------------------------------------------------------- display #
    Component(
        id="ks4010-oled",
        name="OLED Module",
        kits=(KIT,),
        category=Category.display,
        summary="A small I2C graphic display for text and numbers - far more readable than scrolling on the LED matrix.",
        aliases=("oled", "oled display", "oled screen", "ssd1306", "screen"),
        doc_url=DOCS,
        signals=(Signal.i2c,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("SCL - I2C clock", "SDA - I2C data", "V - power", "G - GND"),
            signal_channels=2,
            polarity=Polarity.not_applicable,
        ),
        microbit=MicrobitNotes(
            suggested_pins="SCL to P19, SDA to P20. Nowhere else - that is the micro:bit's I2C bus.",
            avoid_pins="It has no analog or plain digital mode. It will not work on P0-P2.",
            conflicts="Shares the bus with the on-board accelerometer and compass, which is fine, but those pins are then not free.",
            wiring="Four connections: SCL to P19, SDA to P20, V and G.",
        ),
        makecode=CodeNotes(extension="Needs an OLED extension. There are no built-in blocks.", write="Extension blocks for clearing, positioning and writing a string."),
        micropython=CodeNotes(notes="Needs a driver from the lesson - there is no OLED support built into micro:bit MicroPython."),
        teaching=Teaching(
            beginner="Two wires carry addressed messages to the screen. That is I2C: several devices sharing one pair of wires, each with its own address.",
            mistakes=("Wiring it to P0/P1 like a sensor.", "Forgetting the extension and wondering where the blocks are."),
            troubleshooting=("Blank screen: SCL and SDA swapped, or the extension's address does not match the module's.",),
            terms=("I2C", "SCL", "SDA", "address"),
        ),
        verification=PART_TYPE,
    ),
    Component(
        id="ks4010-display",
        name="Display Module",
        kits=(KIT,),
        category=Category.display,
        summary="A four-digit seven-segment display, driven over two wires by its own controller chip.",
        aliases=("display module", "seven segment", "7 segment", "tm1637", "digit display", "4 digit"),
        model="TM1637 type",
        doc_url=DOCS,
        signals=(Signal.digital_out,),
        electrical=Electrical(
            operating_voltage="3.3-5 V",
            pins=("CLK - clock", "DIO - data", "V - power", "G - GND"),
            signal_channels=2,
            polarity=Polarity.not_applicable,
        ),
        microbit=MicrobitNotes(
            suggested_pins="Any two digital pins for CLK and DIO. They are not the I2C bus, despite looking similar.",
            wiring="Four connections: CLK, DIO, V, G. CLK and DIO are not interchangeable.",
        ),
        makecode=CodeNotes(extension="Needs a TM1637 extension.", write="Extension blocks show a number, set brightness, or write individual digits."),
        micropython=CodeNotes(notes="Needs a driver from the lesson."),
        teaching=Teaching(
            beginner="The chip on the back does the work of lighting twenty-eight segments, so the micro:bit only has to send the number.",
            mistakes=("Wiring CLK and DIO to P19/P20 assuming it is I2C. It is a two-wire protocol of its own.",),
        ),
        verification=PART_TYPE,
    ),
    # ------------------------------------------------------------------ passive #
    Component(
        id="ks4010-dupont",
        name="40-pin Female-to-Female Dupont Jumper Wires",
        kits=(KIT,),
        category=Category.passive,
        summary="This kit's only wiring. Female on both ends, because both the shield and the modules present male pins.",
        aliases=("dupont wires", "jumper wires", "dupont", "jumper cables"),
        signals=(Signal.none,),
        electrical=Electrical(polarity=Polarity.not_applicable),
        teaching=Teaching(
            mistakes=("Asking for male-to-female wires. Both ends here are female, and there is no breadboard in this kit to need anything else.",),
        ),
        verification=KEYESTUDIO,
    ),
    Component(
        id="ks4010-usb-cable",
        name="USB Cable",
        kits=(KIT,),
        category=Category.passive,
        summary="Programs and powers the micro:bit from a computer.",
        aliases=("usb cable",),
        signals=(Signal.none,),
        electrical=Electrical(operating_voltage="5 V from USB", polarity=Polarity.not_applicable),
        verification=KEYESTUDIO,
    ),
    Component(
        id="ks4010-battery-holder",
        name="6 x AA Battery Holder",
        kits=(KIT,),
        category=Category.passive,
        summary="The external supply for the shield - what the servo, fan, relay and MQ sensors should be running from.",
        aliases=("battery holder", "battery pack", "6 aa", "external power"),
        signals=(Signal.none,),
        electrical=Electrical(
            operating_voltage="About 9 V from six AA cells, into the shield's regulated external input",
            polarity=Polarity.not_applicable,
            current_notes="This is what makes motors and heated sensors workable. It goes into the shield's power input, never into a 3V pin.",
        ),
        teaching=Teaching(
            safety="Into the shield's own power input only. Nine volts onto a 3V rail or a GPIO pin destroys the micro:bit.",
        ),
        verification=KEYESTUDIO,
    ),
)
