"""ict fair sections

Groups ICT Fair projects into named sections, each belonging to one school and
covering one or more grades. Schools do not share fair projects, so the section
is what carries the school and decides who may see a project.

`fair_projects.section_id` is nullable: any project uploaded before this
migration keeps working and simply has no section yet. It also has no school as
a result, so it is shown to super-admins to be filed and to no teacher —
scoping fails closed rather than guessing.

Revision ID: 42958f0e7fe1
Revises: ecdcb1245c53
Create Date: 2026-09-02 16:32:36.708870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42958f0e7fe1'
down_revision: Union[str, None] = 'ecdcb1245c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fair_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('blurb', sa.String(length=300), nullable=True),
    sa.Column('grades', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fair_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fair_sections_school_id'), ['school_id'], unique=False)

    with op.batch_alter_table('fair_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fair_projects_section_id'), ['section_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_fair_projects_section_id', 'fair_sections', ['section_id'], ['id'],
            ondelete='RESTRICT',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fair_projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fair_projects_section_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fair_projects_section_id'))
        batch_op.drop_column('section_id')

    with op.batch_alter_table('fair_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fair_sections_school_id'))

    op.drop_table('fair_sections')
    # ### end Alembic commands ###
